name: Photoelasticity CI

jobs:

  uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
  ruff:
    runs-on: ubuntu-latest
    name: ruff
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3